---
# title: "LetterBoxed"
# author: "Mohit Shukla"
# date: '2022-08-05'
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This document is created as a help to the NYTimes [LetterBoxed Game](https://www.nytimes.com/puzzles/letter-boxed). In the game, the user has to create words where consecutive letters are not from the same side. 

This tool helps the user list all such words.


```{r formulas, include=FALSE}
library(words)
library(tidyverse)
library(shinydashboard)


`%!in%` <- Negate(`%in%`)
L=3 # min length

W = words::words
W$word = W$word %>% str_to_upper
W = W[W$word_length>=max(L,1),1] %>% unlist
```

If you need more solving tips, [this NYT article can help](https://www.nytimes.com/2022/01/19/crosswords/letter-boxed-tips-and-tricks.html).


## Select Inputs Letters

```{r input1, echo=FALSE}
inputPanel(
  # box(width='100%', title = h3("INPUT LETTERS"),
      # splitLayout(
        selectizeInput(inputId="L1", label=h4("TOP"), LETTERS, selected=NULL, multiple=TRUE, options=NULL),
        selectizeInput(inputId="L2", label=h4("LEFT"), LETTERS, selected=NULL, multiple=TRUE, options=NULL),
        selectizeInput(inputId="L3", label=h4("RIGHT"), LETTERS, selected=NULL, multiple=TRUE, options=NULL),
        selectizeInput(inputId="L4", label=h4("BOTTOM"), LETTERS, selected=NULL, multiple=TRUE, options=NULL),
  # ))
)
```


## Select First Word

```{r input2, echo=FALSE}
inputPanel(
  textInput(inputId="M1", label=h4("First Word Created"))
)
```


```{r, echo=FALSE}
  L5 = reactiveValues( c(input$L1, input$L2, input$L3, input$L4))
  L6 = LETTERS[which(LETTERS %!in% L5)]
  W = W[!grepl(paste0(L6, collapse = '|'), W, ignore.case = TRUE)]

  W1 = c()
  for (Wrd in W) {
    X = strsplit(Wrd,"") %>% unlist
    Y = TRUE
    Z = (match(X,L5)-1) %/% 3
    
    for (i in 2:length(Z)) {
      if (Z[i-1] == Z[i]) {
        Y = FALSE
        break
      }
      }
    
    if (Y) {
      W1 = c(Wrd, W1)
    }
    }
  
  Unq_chr = function(Wrd){
    W1 = str_split(Wrd, "") %>% unlist
    W2 = unique(W1)
    length(W2)
    }
```


## All possible Words

```{r output1, echo=FALSE}
renderText({

  
  WL1 = lapply(W1, Unq_chr) %>% unlist
  WL2 = lapply(W1, str_length) %>% unlist
  Wx = data.table::data.table(W1, WL1, WL2)
  Wx[, Wr := WL1/WL2]
  Wx = Wx[order(WL1, Wr, decreasing = TRUE),]
  W_out = Wx$W1 %>% unique
  
  W_out
})
```


## Previous Word(s)

```{r output2, echo=FALSE}
renderText({
  M2 = str_split(str_to_upper(input$M1), "") %>% unlist

  # M2 = str_split(str_to_upper(a), "") %>% unlist
  C_beg = first(M2)     # First letter
  C_end = last(M2)      # Last letter
  
  L_rem = L5[which(L5 %!in% M2)]
  L_rem_beg = paste0(c(C_beg, L_rem), collapse = '|')
  
  W_filter_beg = W1[str_sub(W1, 1, 1) == C_beg]
  W_filter_beg = W_filter_beg[grepl(L_rem_beg, W_filter_beg, ignore.case = TRUE)] %>% rev
  
  W_filter_beg
})
```

## Next Word(s)

```{r output3, echo=FALSE}
renderText({
  # M2 = str_split(str_to_upper(input$M1), "") %>% unlist
  # C_beg = first(M2)     # First letter
  # C_end = last(M2)      # Last letter
  # 
  # L_rem = L5[which(L5 %!in% M2)]
  L_rem_end = paste0(c(C_end, L_rem), collapse = '|')
  
  W_filter_end = W1[str_sub(W1, 1, 1) == C_end]
  W_filter_end = W_filter_end[grepl(L_rem_end, W_filter_end, ignore.case = TRUE)] %>% rev
  
  W_filter_end
})
```